spring:
  main:
    web-application-type: none
  config:
    import: optional:file:.env[.properties]
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 2000ms
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}
      authentication-database: ${MONGODB_AUTHENTICATION_DATABASE}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      auto-index-creation: false
      uuid-representation: standard

encryption:
  password: ${ENCRYPTION_PASSWORD}
  salt: ${ENCRYPTION_SALT}

github:
  api:
    base-url: https://api.github.com
    graphql-url: https://api.github.com/graphql
    rate-limit:
      threshold: 100

harvester:
  redis:
    stream:
      key: github:collection:trigger
      consumer-group: harvester-group
      consumer-name: ${HOSTNAME:harvester-1}

logging:
  level:
    root: INFO
    io.swkoreatech.kosp.harvester: DEBUG
    org.springframework.batch: INFO
