encryption:
  password: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
  salt: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

jwt:
  secret-key: EXAMPLE7A3E4F37B3DAD9CD8KEY6AA4B1AF7123!@#
  expiration-time:
    access-token: 600000 # (ms) = 10 mins
    refresh-token: 2592000000 # (ms) = 30 days
    signup-token: 1800000 # (ms) = 30 mins

aws:
  access-key: AAAAAAAAAAAAAAAAAAAA
  secret-key: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  region: ap-northeast-2
  s3:
    bucket: dev-kosp

cors:
  allowed-origins:
    - "*"

spring:
  profiles:
    active: local
  web:
    resources:
      add-mappings: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate
  thymeleaf:
    prefix: "classpath:/mail/"
    suffix: ".html"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  batch:
    jdbc:
      initialize-schema: never
      table-prefix: kosp_batch.BATCH_
  security:
    oauth2:
      client:
        registration:
          github:
            client-name: Github
            authorization-grant-type: authorization_code
            scope: read:user, user:email, repo
            client-id: AAAAAAAAAAAAAAAAAAAA
            client-secret: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

  data:
    redis:
      port: 6379
      host: localhost
    mongodb:
      host: localhost
      port: 27017
      database: kosp
      auto-index-creation: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kosp?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: "root"
    password: ""

server:
  tomcat:
    max-http-form-post-size: 10MB
  #  MockMvc이용하면 한글 깨지는 문제 해결하는 설정
  servlet:
    encoding:
      force-response: true

logging:
  level:
    org:
      springframework:
        transaction: DEBUG  # 스프링 트랜잭션 관련 로그 출력
        orm.jpa.JpaTransactionManager: DEBUG
        security: DEBUG
      hibernate:
        engine:
          transaction:
            internal: DEBUG  # Hibernate 트랜잭션 로그 상세 출력
        type:
          descriptor:
            sql: trace

github:
  api:
    base-url: https://api.github.com
    graphql-url: https://api.github.com/graphql
    rate-limit:
      threshold: 100  # API 호출 여유분
