spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 2000ms
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}
      authentication-database: ${MONGODB_AUTHENTICATION_DATABASE}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      auto-index-creation: false
      uuid-representation: standard

logging:
  level:
    io.swkoreatech.kosp.harvester: DEBUG
    org.springframework.batch: DEBUG
    org:
      springframework:
        transaction: DEBUG
        orm.jpa.JpaTransactionManager: DEBUG
      hibernate:
        engine:
          transaction:
            internal: DEBUG
        type:
          descriptor:
            sql: trace
