services:
  mysql:
    image: mysql:8.4.7
    container_name: mysql-kosp-stage-compose
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_VOLUME_PATH}:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: "unless-stopped"

  redis:
    image: valkey/valkey:8.1.4
    container_name: redis-kosp-stage-compose
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${REDIS_VOLUME_PATH}:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: "unless-stopped"

  mongo:
    image: mongo:8.2.2
    container_name: mongo-kosp-stage-compose
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ${MONGO_VOLUME_PATH1}:/data/db
      - ${MONGO_VOLUME_PATH2}:/data/configdb
    command: ["mongod", "--auth", "--bind_ip_all"]
    restart: "unless-stopped"
