services:
  postgres:
    image: postgres:18.1
    container_name: postgres-kosp-stage-compose
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_VOLUME_PATH}:/var/lib/postgresql/data
    restart: "unless-stopped"

  redis:
    image: valkey/valkey:8.1.4
    container_name: redis-kosp-stage-compose
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${REDIS_VOLUME_PATH}:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: "unless-stopped"

  mongo:
    image: mongo:8.2.2
    container_name: mongo-kosp-stage-compose
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ${MONGO_VOLUME_PATH1}:/data/db
      - ${MONGO_VOLUME_PATH2}:/data/configdb
    command: ["mongod", "--auth", "--bind_ip_all"]
    restart: "unless-stopped"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-kosp-stage-compose
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT}:5672"
    volumes:
      - ${RABBITMQ_VOLUME_PATH}:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
    restart: "unless-stopped"
