[versions]
spring-boot = "3.5.7"
dependency-management = "1.1.7"
jjwt = "0.12.3"
webmvc-ui = "2.8.14"
awssdk = "2.40.16"

[libraries]
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }

spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis" }
spring-boot-starter-data-mongodb = { module = "org.springframework.boot:spring-boot-starter-data-mongodb" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-aop = { module = "org.springframework.boot:spring-boot-starter-aop" }
spring-boot-starter-batch = { module = "org.springframework.boot:spring-boot-starter-batch" }

springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "webmvc-ui" }

spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }

spring-boot-starter-oauth2-client = { module = "org.springframework.boot:spring-boot-starter-oauth2-client" }

jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }

mysql-connector-j = { module = "com.mysql:mysql-connector-j" }
h2database = { module = "com.h2database:h2" }

lombok = { module = "org.projectlombok:lombok" }

spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

spring-boot-starter-thymeleaf = { module = "org.springframework.boot:spring-boot-starter-thymeleaf" }
thymeleaf-extras-springsecurity6 = { module = "org.thymeleaf.extras:thymeleaf-extras-springsecurity6" }

awssdk-ses = { module = "software.amazon.awssdk:ses", version.ref = "awssdk" }

flyway-mysql = { module = "org.flywaydb:flyway-mysql" }

[plugins]
org-springframework-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
io-spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "dependency-management" }
