[versions]
spring-boot = "3.5.7"
dependency-management = "1.1.7"
jjwt = "0.12.3"
webmvc-ui = "2.8.14"
awssdk = "2.40.16"
jsoup = "1.17.2"
rsql-jpa = "6.0.33"

[libraries]
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }

spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis" }
spring-session-data-redis = { module = "org.springframework.session:spring-session-data-redis" }
spring-boot-starter-data-mongodb = { module = "org.springframework.boot:spring-boot-starter-data-mongodb" }
spring-boot-starter-data-mongodb-reactive = { module = "org.springframework.boot:spring-boot-starter-data-mongodb-reactive" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-aop = { module = "org.springframework.boot:spring-boot-starter-aop" }
spring-boot-starter-batch = { module = "org.springframework.boot:spring-boot-starter-batch" }
spring-boot-starter-amqp = { module = "org.springframework.boot:spring-boot-starter-amqp" }

springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "webmvc-ui" }

spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }
spring-security-crypto = { module = "org.springframework.security:spring-security-crypto" }

spring-batch-test = { module = "org.springframework.batch:spring-batch-test" }

spring-boot-starter-oauth2-client = { module = "org.springframework.boot:spring-boot-starter-oauth2-client" }

jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }

postgresql = { module = "org.postgresql:postgresql" }
h2database = { module = "com.h2database:h2" }

lombok = { module = "org.projectlombok:lombok" }

spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

spring-boot-starter-thymeleaf = { module = "org.springframework.boot:spring-boot-starter-thymeleaf" }
thymeleaf-extras-springsecurity6 = { module = "org.thymeleaf.extras:thymeleaf-extras-springsecurity6" }

awssdk-ses = { module = "software.amazon.awssdk:ses", version.ref = "awssdk" }
awssdk-s3 = { module = "software.amazon.awssdk:s3", version.ref = "awssdk" }

flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }

rsql-jpa-spring-boot-starter = { group = "io.github.perplexhub", name = "rsql-jpa-spring-boot-starter", version.ref = "rsql-jpa" }

jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }

[plugins]
org-springframework-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
io-spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "dependency-management" }
