logging:
  level:
    io.swkoreatech.kosp.harvester: DEBUG
    org.springframework.batch: DEBUG
    org:
      springframework:
        transaction: DEBUG
        orm.jpa.JpaTransactionManager: DEBUG
      hibernate:
        engine:
          transaction:
            internal: DEBUG
        type:
          descriptor:
            sql: trace
