spring:
  data:
    mongodb:
      authentication-database: ${MONGODB_AUTHENTICATION_DATABASE}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}

logging:
  level:
    root: INFO
    io.swkoreatech.kosp.harvester: DEBUG
    org.springframework.batch: INFO
